name: release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'     
        required: true

jobs:
  deploy:
    if: contains('refs/heads/main', github.ref)
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: download-artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: nuget_artifact

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Release ${{ github.event.inputs.tag_name }}

      - name: Publish
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}
        run: | 
          dotnet nuget add source --username filipsichm --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/filipsichm/index.json"
          dotnet nuget push nuget_artifact/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"