name: release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'     
        required: true

jobs:
  build:
    if: contains('refs/heads/main', github.ref)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  upload-artifact:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Pack
        run: dotnet pack -c Release DependencyInjection.ServiceRegistration/DependencyInjection.ServiceRegistration.csproj -p:Version='${{ github.event.inputs.tag_name }}'

      - uses: actions/upload-artifact@v2
        with:
          name: nuget_artifact
          path: DependencyInjection.ServiceRegistration/bin/Release/

  release:
    needs: [ upload-artifact ]
    runs-on: ubuntu-latest
    
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: nuget_artifact

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: Release ${{ github.event.inputs.tag_name }}

      - name: Publish
        run: | 
          dotnet nuget add source --username filipsichm --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/filipsichm/index.json"
          dotnet nuget push nuget_artifact/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"