name: upload-artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  upload-artifact:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Pack
        run: dotnet pack -c Release DependencyInjection.ServiceRegistration/DependencyInjection.ServiceRegistration.csproj

      - uses: actions/upload-artifact@v2
        with:
          name: nuget_artifact
          path: DependencyInjection.ServiceRegistration/bin/Release/
